import type { Metadata } from 'next';
import './globals.css';
import openSans from './fonts';

export const metadata: Metadata = {
  title: 'Company: sales management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth" style={{ scrollBehavior: 'smooth' }}>
      <body className={openSans.variable}>
        {children}
      </body>
    </html>
  );
}
